### ISSUE TITLE
getting error while loading pretrained model 

### ISSUE THREAD

**Issue by Alizah-Masood** [mj129/CoANet#1]
I'm unable to load the pretrained model file that you have provided. Can you please check if the file is correctly uploaded or not?
I'm getting the following error while loading the model:

[enforce fail at inline_container.cc:144] . PytorchStreamReader failed reading zip archive: failed finding central directory

will look forward to your response. Thanks.

**Comment by mj129** [comment]
I ran the test code again to load the provided model and did not encounter your problem.
If it is convenient, please provide more information so that I can check it.

**Comment by Alizah-Masood** [comment]
Sorry for inconvenience. I think my file didn't download properly. That's why this error occurred. I tried again and it's working now.
