### ISSUE TITLE
Wanna know more experiment details used in your paper

### ISSUE THREAD

**Issue by WangZX-0630** [mj129/CoANet#2]
Hi, I'm doing research on raod extraction from remote sensing images recently. And I sincerely appreciate your works and suprised at remarkable perfomrance improvement comparing with previous achitectures. And I want to know more details on the experiments done in your paper as following: 

1. The experiment results are obtained from the partitioned and resized validation dataset? Or from the whole dataset which also retained the original size?
2. When you calculated the training and interference time of those models, did you maintain the same batch size of images?
3. Did you use the same data augmentation and post processing published in other model's codes when you test the other model's performance?
4. What kind of skeletonize function is used when you compute Apls metric. Could you publish the codes or name the function you used?

Sincerely hope that you could solve my confusions!

**Comment by mj129** [comment]
Thanks for your attention to our work.
1. For the validation dataset, the images in SapceNet are resized to "1280 × 1280" and the images in DeepGlobe will remain at the original size.
2. We report the training time for images of identical batch size and inference time for one image.
3. When testing the other models' performance, we use data augmentation and post-processing in their released codes.
4. You can refer to (https://github.com/avanetten/cresi/blob/main/cresi/04_skeletonize.py) for the skeletonize.
