### ISSUE TITLE
Question about Figure 4

### ISSUE THREAD

**Issue by ajtao** [mj129/CoANet#9]
In Figure 4 of the paper, it looks to me like the diagram has left out some items.
I've drawn what i think is missing in red. Can you please correct me if this is wrong?

https://imgur.com/a/leR5lpT

**Comment by mj129** [comment]
I have checked Fig. 4 in our paper, and it is correct.
O_{i, j,c} = 1 if the two pixels are road pixels.

**Comment by SaSa-123** [comment]
> In Figure 4 of the paper, it looks to me like the diagram has left out some items. I've drawn what i think is missing in red. Can you please correct me if this is wrong?
> 
> https://imgur.com/a/leR5lpT

Hello! The algorithm in Figure 4 is a bit difficult for me to understand. If possible, could you please explain how you understand it? Thank you very much.
